import Src.Problem1
import Src.Problem10
import Src.Problem11
import Src.Problem14
import Src.Problem15
import Src.Problem2
import Src.Problem3
import Src.Problem31
import Src.Problem32
import Src.Problem4
import Src.Problem5
import Src.Problem6
import Src.Problem7
import Src.Problem8
import Src.Problem9
import Src.README
