name: Update Lean
on:
  # schedule:
  #   - cron: "0 11 * * 4"
  workflow_dispatch:

jobs:
  update_lean:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update Lean project
        uses: Seasawher/lean-update@main # 自前のアクションを使用する
        with:
          on_update_succeeds: pr
          on_update_fails: issue
          update_if_modified: lean-toolchain
