name: Update Lean
on:
  schedule:
    - cron: "0 11 * * 4"
  workflow_dispatch:

jobs:
  update_lean:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update Lean project
        uses: Seasawher/lean-update@main # 自前のアクションを使用する
        with:
          #  Allowed values: "silent", "commit", "issue" or "pr". Default: "commit".
          on_update_succeeds: pr
          # Allowed values: "silent", "issue" or "fail". Default: "issue".
          on_update_fails: issue
          what_to_update: lean-toolchain
